#!/bin/bash

set -e

exec 3>&1
exec 1>&2

set +x

payload=$(mktemp $TMPDIR/hab-resource.XXXXXX)

cat > "${payload}" <&0

cat "${payload}" > /opt/resource/payload.out

source_uri="$(jq -r '.source.bldr_url' < "${payload}")"

if [[ source_uri =~ .*http.* ]]; then
    base_uri=$source_uri
else
    base_uri="https://bldr.habitat.sh/v1/depot"
fi

origin="$(jq -r '.source.origin' < "${payload}")"
name="$(jq -r '.source.name' < "${payload}")"
version="$(jq -r '.source.version' < "${payload}")"
build_id="$(jq -r '.source.build_id' < "${payload}")"
src_platform="$(jq -r '.source.platform' < "${payload}")"

src_channel="$(jq -r '.source.channel' < "${payload}")"

if [[ $src_channel == "null" ]]; then
    channel="stable"
else
    channel=$src_channel
fi

if [[ $src_platform == "null" ]]; then
    platform="x86_64-linux"
else
    platform=$src_platform
fi

release_count=$(curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}"  2>/dev/null | jq .total_count)
range_end=$(curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}"  2>/dev/null | jq .range_end)
range_start=$(curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}"  2>/dev/null | jq .range_start)
per_page=$(( $range_end - $range_start + 1 ))

if [[ release_count > $per_page ]]; then
  release_range=(( $release_count / $per_page * $per_page ))
  curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}?range=${release_range}"  2>/dev/null | jq "[.data | to_entries[] | {\"ref\": (.value.version + \"/\" + .value.release )} ]" >&3
else
  curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}"  2>/dev/null | jq "[.data | to_entries[] | {\"ref\": (.value.version + \"/\" + .value.release )} ]" >&3
fi
